### PR TITLE
Feature proposal: JSON reporter

### PR DESCRIPTION
**Pull request by m-vdb**
Hi there,

Me and my team love what you did with `lettuce`. We've been tweaking it a lot recently and I developed a custom JSON reporter. It's inspired by the xunit reporter except it is not following any standard output. The reason why we needed it is that xunit doesn't reflect the full information of the features / scenarios / steps / outlines / backgrounds.

You can take a look at the `tests/functional/test_jsonreport_output.py` file for output previews. It's fully functionally tested and I added unit tests where I could. Let me know if this is something you would want to merge and I'll provide proper documentation :)

Cheers, and thanks for your work!

### CODE REVIEW

**Comment by m-vdb** [comment]
cc @gabrielfalcao 😄

**Comment by gabrielfalcao** [comment]
great work, I haven't run the code locally yet but the online diff looks good.
I'll merge it up soon.

**Comment by gabrielfalcao** [comment]
closed it by mistake

**Comment by gabrielfalcao** [comment]
just merged and released lettuce 0.2.23 thanks for the patch

**Comment by m-vdb** [comment]
nice thanks for your reactivity :) I'll be working on other patches and I'll propose them to you just in case you're interested!

**Pull request merged**
